### ISSUE TITLE
Schema Evolution Engine

### ISSUE THREAD

**Issue by silvanoneto** [silvanoneto/schema-evolution-engine#1]
## Objetivo
Implementar sistema para evolução de schemas com backward compatibility, automatizando migration tools e validação de compatibilidade entre versões. Este projeto explora como Rust pode oferecer type safety em compile-time para problemas tradicionalmente resolvidos com runtime checks em sistemas baseados em JVM.

## Conceitos Fundamentais

Schema evolution é o processo de modificar estruturas de dados mantendo compatibilidade com versões anteriores. Diferentemente de sistemas que validam compatibilidade em runtime, implementaremos validações em compile-time sempre que possível, detectando breaking changes antes da produção.

Três tipos de compatibilidade serão suportados: backward (novos readers podem ler dados antigos), forward (readers antigos podem ler novos dados) e full (ambas as direções). O objetivo é automatizar a detecção desses tipos através de análise sintática das definições de schema.

### Funcionalidades Core
- [ ] Registro e versionamento de schemas (Avro, Protobuf, JSON Schema)
- [ ] Validação automática de compatibilidade entre versões
- [ ] Geração automática de migration code via procedural macros
- [ ] Storage persistente com indexação por subject/version
- [ ] API REST para operações CRUD de schemas
- [ ] Relatórios de compatibilidade com breaking changes detection

### Arquitetura
```rust
// Estrutura base que separa concerns entre storage, validation e code generation
pub struct SchemaRegistry {
    store: sled::Db,                    // Embedded database para metadata persistence
    validators: HashMap<SchemaFormat, Box<dyn SchemaValidator>>, // Strategy pattern para diferentes formatos
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaVersion {
    pub id: Uuid,                       // Identificador único para esta versão específica
    pub version: semver::Version,       // Semantic versioning para tracking de changes
    pub format: SchemaFormat,           // Enum discriminando entre Avro/Protobuf/JSON
    pub definition: String,             // Raw schema definition
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub compatibility: CompatibilityLevel, // Nível de compatibilidade exigido
}
```

O design utiliza trait objects para extensibilidade, permitindo adicionar novos formatos de schema sem modificar o core engine. Cada validator implementa logic específico para seu formato, enquanto o registry coordena operações cross-format.

### Setup Inicial
```bash
# Rust toolchain com nightly para procedural macros avançados
rustup install nightly
rustup component add clippy rustfmt --toolchain nightly

# Performance tools otimizados para Apple Silicon
cargo install flamegraph
cargo install hyperfine  
cargo install criterion

# Compiladores para schema formats - necessários para validation
brew install protobuf      # Protocol Buffers compiler (protoc)
brew install avro-tools    # Apache Avro tools para validation

# Ferramentas de comparação - instalar Confluent CLI para benchmarks
brew install confluent-cli
```

A instalação do nightly é necessária porque usaremos procedural macros avançados para code generation. O flamegraph ajudará a identificar bottlenecks de performance, enquanto hyperfine fornecerá benchmarks reproduzíveis.

### Cargo.toml
```toml
[package]
name = "schema_evolution_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
# Schema Formats - cada crate lida com parsing e validation de um formato específico
prost = "0.12"              # Protocol Buffers support
avro-rs = "0.16"           # Apache Avro implementation em Rust puro
jsonschema = "0.17"        # JSON Schema Draft 7 validation
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Storage & Serialization - embedded database para evitar dependências externas
sled = "0.34"              # ACID embedded database, boa performance para metadata
bincode = "1.3"            # Binary serialization eficiente para storage interno
uuid = { version = "1.0", features = ["v4"] }

# Code Generation - procedural macros para migration automation
proc-macro2 = "1.0"        # Core procedural macro utilities
quote = "1.0"              # Code generation com syntax highlighting
syn = "2.0"                # Rust syntax tree parsing

# Web API - framework leve para REST endpoints
axum = "0.7"               # Async web framework, successor do warp
tower = "0.4"              # Service abstractions para middleware
tower-http = { version = "0.5", features = ["cors", "fs"] }

# Utilities
chrono = { version = "0.4", features = ["serde"] }
semver = "1.0"             # Semantic versioning parsing e comparison
tracing = "0.1"            # Structured logging
tracing-subscriber = "0.3"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3.0"           # Temporary directories para testes

[[bench]]
name = "schema_validation_benchmark"
harness = false            # Usar criterion ao invés do harness padrão

[lib]
proc-macro = true          # Enable procedural macro support
```

### Branches
```bash
# Organização por domínio técnico para permitir desenvolvimento paralelo
main/
├── develop/
├── feature/schema-storage      # Persistence layer com sled
├── feature/avro-support       # Avro parsing e compatibility rules
├── feature/protobuf-support   # Protobuf parsing e compatibility rules  
├── feature/json-schema-support # JSON Schema Draft 7 support
├── feature/compatibility-checker # Core compatibility algorithm
├── feature/migration-generator   # Procedural macros para code generation
├── feature/rest-api             # HTTP endpoints e OpenAPI spec
└── feature/benchmarks          # Performance comparisons
```

Esta organização permite que diferentes pessoas trabalhem em formatos específicos simultaneamente. O compatibility-checker será desenvolvido após os parsers individuais estarem funcionais.

### Estrutura de Diretórios
```
schema_evolution_engine/
├── src/
│   ├── lib.rs              # Re-exports públicos e documentation
│   ├── registry.rs         # Core SchemaRegistry implementation
│   ├── formats/            # Schema format parsers e validators
│   │   ├── mod.rs         # Common traits e shared utilities
│   │   ├── avro.rs        # Avro-specific implementation  
│   │   ├── protobuf.rs    # Protobuf-specific implementation
│   │   └── json_schema.rs # JSON Schema implementation
│   ├── compatibility/      # Compatibility checking algorithms
│   │   ├── mod.rs         # Public interface e shared types
│   │   ├── checker.rs     # Core compatibility checking logic
│   │   └── rules.rs       # Format-specific compatibility rules
│   ├── migration/          # Code generation para data migration
│   │   ├── mod.rs         # Public procedural macro exports  
│   │   ├── generator.rs   # AST generation logic
│   │   └── macros.rs      # Procedural macro implementations
│   ├── storage/            # Persistence layer
│   │   ├── mod.rs         # Storage trait definitions
│   │   └── sled_store.rs  # Sled-based implementation
│   └── api/                # REST API layer
│       ├── mod.rs         # Router setup e middleware
│       ├── handlers.rs    # HTTP request handlers
│       └── models.rs      # Request/response DTOs
├── benches/
│   └── schema_validation_benchmark.rs # Criterion benchmarks
├── tests/
│   ├── integration_tests.rs      # End-to-end workflow tests
│   ├── compatibility_tests.rs    # Compatibility rule validation
│   └── migration_tests.rs        # Code generation verification
├── examples/
│   ├── basic_registry.rs         # Simple usage example
│   ├── avro_evolution.rs         # Avro schema evolution demo
│   └── protobuf_migration.rs     # Protobuf migration example
├── schemas/                      # Test schemas para benchmarks
│   ├── test_schemas/
│   │   ├── user_v1.avsc         # Avro schema version 1
│   │   ├── user_v2.avsc         # Avro schema version 2 (compatible)
│   │   └── user.proto           # Protobuf equivalent
│   └── benchmarks/               # Large schema sets para performance testing
└── docs/
    ├── BENCHMARK_RESULTS.md      # Performance comparison results
    ├── COMPATIBILITY_RULES.md    # Documentation of compatibility algorithms
    └── MIGRATION_GUIDE.md        # Guide para using generated migration code
```

### Implementação Tipo Rustlings

O sistema de exercícios seguirá uma progressão lógica: parsing básico → validation → compatibility checking → code generation. Cada exercício fornece feedback construtivo ao invés de apenas erros de compilação.

```rust
// exercises/ex01_basic_schema_parsing.rs
// Este exercício ensina parsing básico de JSON Schema
// Complete a função abaixo para extrair o type de um schema JSON
use serde_json::Value;

fn extract_schema_type(schema_str: &str) -> Result<String, serde_json::Error> {
    // Dica: Use serde_json::from_str para parsing e acesse o campo "type"
    // JSON Schema sempre tem um campo "type" no root level
    todo!("Implementar extraction do type field")
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_object_type_extraction() {
        let schema = r#"{"type": "object", "properties": {"name": {"type": "string"}}}"#;
        let result = extract_schema_type(schema).unwrap();
        assert_eq!(result, "object");
    }
    
    #[test] 
    fn test_array_type_extraction() {
        let schema = r#"{"type": "array", "items": {"type": "number"}}"#;
        let result = extract_schema_type(schema).unwrap();
        assert_eq!(result, "array");
    }
}
```

### Progression Tracker
```rust
// src/learning/mod.rs
pub struct SchemaLearningTracker {
    completed_exercises: Vec<String>,
    schema_formats_mastered: HashSet<SchemaFormat>,
    compatibility_rules_learned: Vec<CompatibilityRule>,
    performance_benchmarks: HashMap<String, Duration>,
}

impl SchemaLearningTracker {
    pub fn suggest_next_schema_concept(&self) -> Option<String> {
        // Progressão pedagógica: conceitos simples para complexos
        // JSON Schema (mais familiar) → Avro → Protobuf → Compatibility Rules → Migration Generation
        
        if self.completed_exercises.is_empty() {
            Some("Start with JSON Schema parsing - most similar to regular JSON".to_string())
        } else if !self.schema_formats_mastered.contains(&SchemaFormat::JsonSchema) {
            Some("Master JSON Schema validation before moving to binary formats".to_string())
        } else if !self.schema_formats_mastered.contains(&SchemaFormat::Avro) {
            Some("Learn Avro - it has simpler evolution rules than Protobuf".to_string())
        } else {
            Some("Ready for advanced compatibility checking algorithms".to_string())
        }
    }
}
```

### Ferramentas de Comparação

Este projeto será comparado com schema registries existentes, focando em métricas objetivas de performance. As ferramentas escolhidas representam diferentes arquiteturas: self-hosted (Confluent), managed services (AWS Glue), e solutions complexas (DataHub).

- **Confluent Schema Registry** (Java) - Reference implementation, widely adopted
- **AWS Glue Schema Registry** (Managed service) - Cloud-native approach  
- **Apache Atlas** (Java/Scala) - Enterprise governance focus
- **LinkedIn DataHub** (Java/Python) - Metadata management platform
- **Netflix Metacat** (Java) - Multi-store metadata service

### Cenários de Teste
```bash
# Benchmark será executado com datasets representativos de uso real
# Dataset: 100k schemas de 2KB médio (typical enterprise size)
# Operations: Registration, Compatibility Check, Schema Lookup  
# Hardware: Mac M3 Pro (12 cores, 18GB RAM)
# Métricas: Operations/sec, Memory Usage, Response Time P99

./benchmarks/run_schema_comparison.sh
```

### Scripts de Benchmark
```bash
#!/bin/bash
# benchmarks/run_schema_comparison.sh

echo "=== Rust Schema Evolution Engine Benchmark ==="
echo "Testing with realistic enterprise workload..."

# Schema Registration Performance - measures insert throughput
hyperfine --warmup 3 --runs 10 \
  './target/release/schema_benchmark register --schemas schemas/test_schemas/ --count 10000'

# Compatibility Check Performance - critical for CI/CD pipelines
echo "=== Compatibility Check Performance ==="  
hyperfine --warmup 3 --runs 10 \
  './target/release/schema_benchmark compatibility --schema1 schemas/user_v1.avsc --schema2 schemas/user_v2.avsc'

# Memory usage during bulk operations - important for resource planning
echo "=== Memory Usage Monitoring ==="
/usr/bin/time -l ./target/release/schema_benchmark bulk_register --count 100000
```

### Performance Targets (Mac M3 Pro)

Estes targets são baseados em benchmarks existentes de schema registries e representam performance enterprise-grade necessária para CI/CD pipelines e high-throughput applications.

- [ ] Schema Registration: < 5ms P99 (critical para developer productivity)
- [ ] Compatibility Check: < 1ms P99 (usado em hot paths de serialization)
- [ ] Schema Lookup: < 0.5ms P99 (accessed frequently during deserialization) 
- [ ] Memory usage: < 100MB para 100k schemas (efficient resource utilization)
- [ ] Concurrent operations: > 1000 ops/sec (enterprise load support)

### Funcionalidades
- [ ] Suporte completo para Avro, Protobuf, JSON Schema
- [ ] Compatibility checking com rules configuráveis
- [ ] Migration code generation via procedural macros
- [ ] REST API completa com OpenAPI documentation
- [ ] Persistent storage com crash recovery
- [ ] Structured logging com tracing

### Comparativos
- [ ] Benchmark vs Confluent Schema Registry documentado
- [ ] Análise de trade-offs vs AWS Glue Schema Registry
- [ ] Comparação de features vs DataHub
- [ ] Relatório de performance vs Apache Atlas
- [ ] Cost analysis para self-hosted vs managed solutions

### Código
- [ ] Implementação completa em Rust
- [ ] Procedural macros para migration generation
- [ ] REST API com handlers completos
- [ ] Testes unitários, integração e property-based
- [ ] Benchmarks automatizados

### Documentação
- [ ] README com setup, usage e API documentation
- [ ] BENCHMARK_RESULTS.md com comparativos detalhados
- [ ] COMPATIBILITY_RULES.md explicando regras de compatibilidade
- [ ] MIGRATION_GUIDE.md com exemplos de code generation
- [ ] OpenAPI specification para REST API

### Análise
- [ ] Relatório de performance comparativa vs Schema Registries
- [ ] Análise de trade-offs entre self-hosted vs managed
- [ ] Recomendações para migration strategies
- [ ] Cost-benefit analysis para diferentes scale scenarios
- [ ] Security considerations para schema management

## Comando de Inicialização
```bash
git checkout -b feature/schema-evolution-foundation
cargo new schema_evolution_engine --lib
cd schema_evolution_engine
# Copiar Cargo.toml e estrutura inicial
mkdir -p schemas/test_schemas schemas/benchmarks
cargo test
cargo bench
```

### Schema Registry Performance

Estas estimativas são baseadas em benchmarks públicos de schema registries existentes e testes preliminares com implementações similares em Rust. Os números refletem a expectativa de que Rust oferecerá vantagens significativas em latência e memory usage.

| Operação | Rust Engine | Confluent SR | AWS Glue | DataHub |
|----------|-------------|--------------|----------|---------|
| Schema Registration | 2ms | 15ms | 50ms | 25ms |
| Compatibility Check | 0.5ms | 8ms | 20ms | 12ms |
| Schema Lookup | 0.1ms | 3ms | 10ms | 5ms |
| Memory Usage | 50MB | 512MB | N/A | 1GB |
| Cold Start | 100ms | 5s | N/A | 15s |

A vantagem esperada do Rust vem de: zero garbage collection overhead, efficient memory layout para schemas cached, e compile-time optimizations que JVM-based solutions não conseguem achieve.

---

**Fontes**: Baseado no guia de projetos Rust para engenharia de dados, documentação oficial do Confluent Schema Registry, benchmarks públicos de Apache Avro e Protocol Buffers, e especificações de performance para sistemas de schema management em ambiente enterprise.
